version: 2
jobs:
    bnetserver:
        machine: 
        image: ubuntu-1604:201903-01
        filters:
        branch:
            only: Ashamane
        steps:
        - run:
            name: "Install deps"
            command: |
                wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
                sudo dpkg -i packages-microsoft-prod.deb
                sudo apt-get update
                sudo apt-get install apt-transport-https
                sudo apt-get update
                sudo apt-get install dotnet-sdk-3.1
                sudo apt-get install sshpass
                sudo apt-get install zip gzip tar
        - run:
            name: "Clone & Pull Submodules"
            command: |
                git clone https://github.com/LuigiElleBalotta/CypherCore.git cyphercore --recursive --branch Ashamane
        - run: 
            name: "Compilazione BNetServer"
            command: |
                dotnet publish -c Release -o ../publish/bnetserver cyphercore/Source/BNetServer/BNetServer.csproj
        - run: 
            name: "List files"
            command: |
                ls /home/circleci/publish/bnetserver
        - run: 
            name: "Kill BNetServer"
            command: |
                sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_HOST -o stricthostkeychecking=no 'trap "screen -XS bnetserver quit" QUIT TERM INT EXIT'
        - run: 
            name: "Empty server folder'"
            command: |
                sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_HOST -o stricthostkeychecking=no "cd /home/ubuntu/emu/wow/ && find ./bnetserver -mindepth 1 ! -regex '^./bnetserver/BNetServer.conf' -delete"
        - run: 
            name: "Copy files to server"
            command: |
                sshpass -p $SSH_PASSWORD scp -o stricthostkeychecking=no -r /home/circleci/publish/bnetserver/* $SSH_USER@$SSH_HOST:/home/ubuntu/emu/wow/bnetserver
    worldserver:
        machine: 
            image: ubuntu-1604:201903-01
        filters:
            branch:
            only: Ashamane
        steps:
            - run:
                name: "Install deps"
                command: |
                    wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
                    sudo dpkg -i packages-microsoft-prod.deb
                    sudo apt-get update
                    sudo apt-get install apt-transport-https
                    sudo apt-get update
                    sudo apt-get install dotnet-sdk-3.1
                    sudo apt-get install sshpass
                    sudo apt-get install zip gzip tar
            - run:
                name: "Clone & Pull Submodules"
                command: |
                    git clone https://github.com/LuigiElleBalotta/CypherCore.git cyphercore --recursive --branch Ashamane
            - run: 
                name: "Compilazione WorldServer"
                command: |
                    dotnet publish -c Release -o ../publish/worldserver cyphercore/Source/WorldServer/WorldServer.csproj
            - run: 
                name: "List files"
                command: |
                    ls /home/circleci/publish/worldserver
            - run: 
                name: "Kill WorldServer"
                command: |
                    sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_HOST -o stricthostkeychecking=no 'trap "screen -XS worldserver quit" QUIT TERM INT EXIT'
            - run: 
                name: "Empty server folder'"
                command: |
                    sshpass -p $SSH_PASSWORD ssh $SSH_USER@$SSH_HOST -o stricthostkeychecking=no "cd /home/ubuntu/emu/wow/ && find ./worldserver -mindepth 1 ! -regex '^./worldserver/WorldServer.conf' -delete"
            - run: 
                name: "Copy files to server"
                command: |
                    sshpass -p $SSH_PASSWORD scp -o stricthostkeychecking=no -r /home/circleci/publish/worldserver/* $SSH_USER@$SSH_HOST:/home/ubuntu/emu/wow/worldserver

workflows:
    version: 2
    deploy:
        jobs:
            - bnetserver:
                filters: 
                    branches: 
                        only: 
                            - Ashamane
                context: LuigiElleBalotta
            - worldserver:
                requires: 
                    - bnetserver
                filters: 
                    branches:
                        only:
                            - Ashamane
                context: LuigiElleBalotta